version: '3'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: it_web
      MYSQL_USER: hku
      MYSQL_PASSWORD: 123456789

  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - '80:80'
    depends_on:
      - node