name: CI/CD - Develop

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Los pasos son los mismos que en el flujo de trabajo de la rama `main`
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build

      - name: Set up Docker
        uses: docker/setup-docker@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: your-dockerhub-username/it-support-app:${{ github.sha }}

      - name: Deploy to server
        run: |
          ssh user@your-server-ip "docker stop it-support-app && docker rm it-support-app || true"
          ssh user@your-server-ip "docker pull your-dockerhub-username/it-support-app:${{ github.sha }}"
          ssh user@your-server-ip "docker run -d --name it-support-app -p 80:80 your-dockerhub-username/it-support-app:${{ github.sha }}"
